<error errorId="20c0cb6d-7d18-4e5b-b180-0b395cd2f082" host="CHENSHIYI-PC" type="System.NullReferenceException" message="未将对象引用设置到对象的实例。" source="MedicalInsuranceService" detail="System.NullReferenceException: 未将对象引用设置到对象的实例。&#xD;&#xA;   在 MedicalInsuranceService.Filter.DeflateCompressionAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext) 位置 E:\源代码\阳光医保接口\MedicalInsuranceService\MedicalInsuranceService\Filter\DeflateCompressionAttribute.cs:行号 16&#xD;&#xA;   在 System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken)&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()&#xD;&#xA;   在 System.Web.Http.Filters.ActionFilterAttribute.&lt;CallOnActionExecutedAsync&gt;d__5.MoveNext()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   在 System.Web.Http.Filters.ActionFilterAttribute.&lt;ExecuteActionFilterAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   在 System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- 引发异常的上一位置中堆栈跟踪的末尾 ---&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA;   在 System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" time="2015-12-02T01:19:01.9083864Z" />